project:
  type: website
  output-dir: docs

website:
  title: "STA 529 2.0 Data Mining"
  site-url: "https://thiyangt.github.io/Data.Mining/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

